-- ta bugando nao sei pq
-- require("ibl").setup({
-- 	indent = { char = "▏" },
-- 	-- char_blankline = " ",
-- 	exclude = {
-- 		filetypes = { "help", "terminal", "lspinfo", "TelescopePrompt", "TelescopeResults" },
-- 		buftypes = { "terminal" },
-- 	},
-- 	-- show_first_indent_level = false,
-- 	-- show_current_context = true,
-- 	-- show_current_context_start = true,
--     })
